### ISSUE TITLE
Chartboost doesn't call ChartboostDelegateAdapter.didCompleteRewardedVideo(...)

### ISSUE THREAD

**Issue by wsrdzg** [robovm/robovm-robopods#25]
I watch a rewarded video but no method of ChartboostDelegateAdapter is called except for didCacheRewardedVideo(...). That's a problem, because I need to know if the user has completed the rewarded video.

**Comment by tajny** [comment]
any progress on this ?

**Comment by BlueRiverInteractive** [comment]
No progress yet, I'm afraid. 

I quickly took a look at where the ChartboostDelegate is used and it seems that you can only specify it when you initialize Chartboost. That's certainly an issue because the delegate object will be passed to native but is nowhere referenced on the Java side. So the GC will collect the delegate after some time.

I'm not sure if this will solve this particular issue but you could try to store your ChartboostDelegateAdapter object as a class field. At least this should prevent the GC from collecting it to early.

**Comment by tajny** [comment]
Yes, you're right it is garbage collected, after making  final field with it it works as expected:))

**Comment by BlueRiverInteractive** [comment]
Awesome! I will add this fix to the robopod then.
