### ISSUE TITLE
Google-Analytics causes error in iTunes: Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.

### ISSUE THREAD

**Issue by AgrarPirat** [robovm/robovm-robopods#33]
Hello RoboVM team,

initializing the Google Analytics binding like the following:
```
         GAI gai = GAI.getSharedInstance();
         GAITracker appTracker = gai.getTracker(ANALYTICS_IOS);
         appTracker.setAllowsIDFACollection(false);

         gai.setDefaultTracker(appTracker);
         gai.enableCrashReporting();
         gai.setTracksUncaughtExceptions(true);
         gai.setDispatchInterval(DISPATCH_PERIOD);
         gai.setDryRun(false);
         gai.getLogger().setLogLevel(GAILogLevel.Verbose);
```

Causes the following error message in iTunes when the App is submitted for review:

```
Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.
```

Do you have any ideas how the use of the IDFA can be disabled in the Google Analytics RoboPod? The call `appTracker.setAllowsIDFACollection(false);` seems to have no effect.
Any advice is welcome.
Thanks in advance.

**Comment by vetrovosk** [comment]
we are getting the same warning. is there any known workarounds for this?

**Comment by mikemee** [comment]
Per https://developers.google.com/analytics/devguides/collection/ios/v3/optional-features and https://stackoverflow.com/questions/30880958/google-analytics-idfa-usage-on-ios, have you tried removing:

    libAdIdAccess.a
    AdSupport.framework

You may have to manually download the pod and install it into your app as files and then remove the `libAdIdAccess.a` file and change the plist setting for `AdSupport.framework`.

I had to do something similar for the Flurry library because it also uses IDFA by default because it assumes ads, but you can remove it and then submit ok.

Ideally there would be two variations of the pod.

**Comment by BlueRiverInteractive** [comment]
There are now 2 versions of the Google Analytics RoboPod: iOS and iOS-noads. If you don't want to use ads in your app, you can now use the `robopods-google-analytics-ios-noads` artifact instead to fix the IDFA issue.
https://github.com/robovm/robovm-robopods/tree/master/google-analytics
