### ISSUE TITLE
Facebook 1.12.0+ is using the web login instead of native

### ISSUE THREAD

**Issue by WillCalderwood** [robovm/robovm-robopods#88]
Following on from [this](https://github.com/robovm/robovm-robopods/issues/77)

I've been through all the documentation. The only changes recently were for iOS 9, but I'd already implemented all of those and they were working fine. I've spent most of the day fiddling with my setup and can't get the native login to show on iOS 9 with the 1.12+ (All other combinations work).

My code still works ok on iOS 7 with 1.13.0, so it might be something related to my iOS 9 setup, but all was working fine until I upgraded to 1.12.0 of the SDK.

One difference I have noticed between the versions of the SDK is that 1.9.0 and below call `openURL` but this doesn't occur in 1.12.0+ (I'm not sure what should be occurring). The latest [SDK documentation](https://developers.facebook.com/docs/facebook-login/ios#custom-login-button) just says to call `logInWithReadPermissions`. 

Has anyone else got this working? Is it definitely my setup that's the problem here?

**Comment by BlueRiverInteractive** [comment]
What login behavior do you specify on your FBSDKLoginManager?
Please look at this api documentation: https://developers.facebook.com/docs/reference/ios/current/class/FBSDKLoginManager/
And:
https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.h#L72

Also how is your `Info.plist.xml` looking? There are a few things you need to specify to make everything work seamlessly:
```plist
<key>FacebookAppID</key>
<string>YOUR_FB_APP_ID</string>
<key>FacebookDisplayName</key>
<string>YOUR_FB_APP_NAME</string>

<key>NSAppTransportSecurity</key>
<dict>
      <key>NSAllowsArbitraryLoads</key>
      <true />
</dict>
<key>LSApplicationQueriesSchemes</key>
<array>
      <string>fbapi</string>
      <string>fb-messenger-api</string>
      <string>fbauth2</string>
      <string>fbshareextension</string>
</array>
```

`NSAppTransportSecurity` and `LSApplicationQueriesSchemes` is required to make it work on iOS 9. __Always remember__: If you specify `NSAllowsArbitraryLoads` with `true` in `NSAppTransportSecurity` __NEVER__ add any other exceptions to `NSAppTransportSecurity` otherwise `NSAllowsArbitraryLoads` will be ignored!!!

**Comment by WillCalderwood** [comment]
@BlueRiverInteractive  My `NSAppTransportSecurity` was as specified https://developers.facebook.com/docs/ios/ios9 but I've changed to look like your suggestion.

Also just stumbled across [this](http://stackoverflow.com/questions/32299271/facebook-sdk-login-never-calls-back-my-application-on-ios-9), note the comment 

> In SDK v4.6 and v3.24, the FB SDK uses Safari View Controller by default rather than fast-app-switching to the native Facebook app. This is by design, and because on iOS 9, Safari View Controller offers a better experience for people than the fast-app-switch flow.

So this is now the way it's done. I also had to update my openURL to do the following:

    @Override
    public boolean openURL(UIApplication app, NSURL url, UIApplicationOpenURLOptions options) {
        if (app.canOpenURL(url))
            return FBSDKApplicationDelegate.getSharedInstance().openURL(app, url, options.getSourceApplication(), (NSPropertyList) options.getAnnotation());

        return false;
    }

It now appears to be working as expected, just not as it used to.

Thanks for you help with this.
